name: docker
services:
  laguna-s-2.1-118b-q4km--llamacpp-laguna-fork-vulkan-dflash-strix-apu-v2:
    image: strix-halo-r9700-llm-builds/llamacpp-laguna-fork:vulkan-radv
    container_name: laguna-s-2.1-118b-q4km--llamacpp-laguna-fork-vulkan-dflash-strix-apu-v2
    devices:
    - /dev/kfd:/dev/kfd
    - /dev/dri:/dev/dri
    group_add:
    - '26'
    - '303'
    volumes:
    - /var/lib/ai-models/laguna-s-2.1-118b-q4km:/models:ro
    - /var/lib/ai-models/laguna-s-2.1-dflash-draft-quant:/models-draft:ro
    command: '/build/build/bin/llama-server -m /models/UD-Q4_K_M/Laguna-S-2.1-UD-Q4_K_M-00001-of-00003.gguf
      -md /models-draft/laguna-s-2.1-DFlash-Q4_K_M.gguf --spec-type draft-dflash --spec-draft-n-max
      2 -ngl 999 -fa 1 --swa-full --reasoning-format deepseek -np 1 -c 131072 -n 8192
      -ctk q8_0 -ctv q8_0 --host 0.0.0.0 --port 8080 -a laguna-dflash-vulkan-v2 --metrics

      '
    ports:
    - 127.0.0.1:8125:8080
