name: docker
services:
  qwen3.8-27b-q4km--llamacpp-vulkan-radv-r9700-v1:
    image: docker.io/kyuz0/amd-strix-halo-toolboxes:vulkan-radv
    container_name: qwen3.8-27b-q4km--llamacpp-vulkan-radv-r9700-v1
    devices:
    - /dev/kfd:/dev/kfd
    - /dev/dri:/dev/dri
    group_add:
    - '26'
    - '303'
    volumes:
    - /var/lib/ai-models/qwen3.8-27b-q4km:/models:ro
    command: 'llama-server -m /models/Qwen3.8-27B-Q4_K_M.gguf -dev Vulkan0 -ngl 999
      -fa 1 -np 1 -c 131072 -n 8192 -ctk q8_0 -ctv q8_0 --host 0.0.0.0 --port 8080
      -a qwen3.8-27b-q4km-r9700 --metrics

      '
    ports:
    - 127.0.0.1:8132:8080
