name: docker
services:
  laguna-s-2.1-118b-q4km--llamacpp-laguna-fork-rocm-dflash-strix-apu-v1:
    image: strix-halo-r9700-llm-builds/llamacpp-laguna-fork:rocm-7.14
    container_name: laguna-s-2.1-118b-q4km--llamacpp-laguna-fork-rocm-dflash-strix-apu-v1
    devices:
    - /dev/kfd:/dev/kfd
    - /dev/dri:/dev/dri
    group_add:
    - '26'
    - '303'
    volumes:
    - /var/lib/ai-models/laguna-s-2.1-118b-q4km:/models:ro
    - /var/lib/ai-models/laguna-s-2.1-dflash-draft:/models-draft:ro
    command: '/build/build/bin/llama-server -m /models/UD-Q4_K_M/Laguna-S-2.1-UD-Q4_K_M-00001-of-00003.gguf
      -md /models-draft/laguna-s-2.1-DFlash-BF16.gguf --spec-type draft-dflash --spec-draft-n-max
      15 -ngl 999 -fa 0 --swa-full --reasoning-format deepseek -np 1 -c 131072 -n
      8192 -ctk q8_0 -ctv q8_0 --host 0.0.0.0 --port 8080 -a laguna-dflash-rocm --metrics

      '
    ports:
    - 127.0.0.1:8123:8080
