name: docker
services:
  qwen3.6-35b-a3b--vllm-therock-gfx1151-strix-apu-v1:
    image: docker.io/kyuz0/vllm-therock-gfx1151:latest
    container_name: qwen3.6-35b-a3b--vllm-therock-gfx1151-strix-apu-v1
    devices:
    - /dev/kfd:/dev/kfd
    - /dev/dri:/dev/dri
    group_add:
    - video
    - render
    security_opt:
    - seccomp:unconfined
    ipc: host
    volumes:
    - /var/lib/ai-models:/models
    - vllm-qwen3.6-35b-a3b-cache:/root/.cache/vllm
    command: 'vllm serve /models/qwen3.6-35b-a3b --served-model-name qwen3.6-35b-a3b
      --host 0.0.0.0 --port 8000 --tensor-parallel-size 1 --gpu-memory-utilization
      0.70 --dtype auto --trust-remote-code --max-num-seqs 64 --enable-prefix-caching
      --max-model-len 131072 --enable-auto-tool-choice --tool-call-parser qwen3_coder
      --reasoning-parser qwen3

      '
    ports:
    - 127.0.0.1:8000:8000
volumes:
  vllm-qwen3.6-35b-a3b-cache:
    external: true
    name: docker_vllm-qwen3.6-35b-a3b-cache
