services:
  occamy-1.0-mtp-q6--llamacpp-vulkan-radv-strix-apu-v1:
    image: docker.io/kyuz0/amd-strix-halo-toolboxes:vulkan-radv
    container_name: occamy-1.0-mtp-q6--llamacpp-vulkan-radv-strix-apu-v1
    labels:
      com.local-ai-machine.always-up: "false"
    devices:
    - /dev/kfd:/dev/kfd
    - /dev/dri:/dev/dri
    group_add:
    - '26'
    - '303'
    volumes:
    - /var/lib/ai-models/occamy-1.0-mtp-q6:/models:ro
    - /var/lib/ai-models/occamy-1.0-mmproj:/mmproj:ro
    command: 'llama-server -m /models/occamy-1.0-mtp-Q6_K.gguf -dev Vulkan1
      -ngl 999 -fa 1 --spec-type draft-mtp --spec-draft-n-max 2 --spec-draft-p-min
      0.3 -np 3 --kv-unified --kv-unified-per-slot 262144 -n 8192 -ctk q8_0 -ctv q8_0
      --cache-ram 32768
      --mmproj /mmproj/mmproj-occamy-1.0-F16.gguf --mmproj-device Vulkan1
      --host 0.0.0.0
      --port 8080 -a occamy-1.0-mtp-q6 --metrics

      '
    ports:
    - 127.0.0.1:8205:8080
