name: docker
services:
  gpt-oss-120b--llamacpp-vulkan-radv-strix-apu-v1:
    image: docker.io/kyuz0/amd-strix-halo-toolboxes:vulkan-radv
    container_name: gpt-oss-120b--llamacpp-vulkan-radv-strix-apu-v1
    devices:
    - /dev/kfd:/dev/kfd
    - /dev/dri:/dev/dri
    group_add:
    - '26'
    - '303'
    volumes:
    - /var/lib/ai-models/llamacpp-gpt-oss-120b:/models:ro
    command: 'llama-server -m /models/gpt-oss-120b-MXFP4.gguf -dev Vulkan1 -ngl 999
      -fa 1 -np 1 -c 131072 -n 8192 -ctk q8_0 -ctv q8_0 --host 0.0.0.0 --port 8080
      -a gpt-oss-120b-llamacpp --metrics

      '
    ports:
    - 127.0.0.1:8116:8080
