name: docker
services:
  laguna-s-2.1-118b-q4km--llamacpp-vulkan-radv-speculative-xs-strix-apu-v1:
    image: docker.io/kyuz0/amd-strix-halo-toolboxes:vulkan-radv
    container_name: laguna-s-2.1-118b-q4km--llamacpp-vulkan-radv-speculative-xs-strix-apu-v1
    devices:
    - /dev/kfd:/dev/kfd
    - /dev/dri:/dev/dri
    group_add:
    - '26'
    - '303'
    volumes:
    - /var/lib/ai-models/laguna-s-2.1-118b-q4km:/models-s:ro
    - /var/lib/ai-models/laguna-xs-2.1-33b-q4km:/models-xs:ro
    command: 'llama-server -m /models-s/UD-Q4_K_M/Laguna-S-2.1-UD-Q4_K_M-00001-of-00003.gguf
      -dev Vulkan1 -md /models-xs/Laguna-XS-2.1-Q4_K_M.gguf --spec-type draft-simple
      -ngl 999 -fa 1 --reasoning-format deepseek -n 8192 -c 8192 --host 0.0.0.0 --port
      8080 -a laguna-s-2.1-118b-speculative-xs --metrics

      '
    ports:
    - 127.0.0.1:8107:8080
